export const alumniData = [
  {
    id: "1",
    name: "Kaushik Arora",
    batch: "2023-26",
    bio: "Former Executive Board Member at ISTE TIET.",
    image: "/Alumni/KaushikArora.jpg",
  },
  {
    id: "2",
    name: "Lakshita Gupta",
    batch: "2023-26",
    bio: "Former Executive Board Member at ISTE TIET.",
    image: "/Alumni/LakshitaGupta.jpg",
  },
  {
    id: "3",
    name: "Bhavya",
    batch: "2023-2026",
    image: "/Alumni/Bhavya.jpg",
    bio: "Former Executive Board Member at ISTE TIET.",
  },
  {
    id: "4",
    name: "Ishita Singh Oberoi",
    batch: "2023-26",
    image: "/Alumni/IshitaOberoi.jpg",
    bio: "Former Executive Board Member at ISTE TIET.",
  },
  {
    id: "5",
    name: "Abhivinesh Sharma",
    batch: "2023-26",
    image: "/Alumni/AbhivineshSharma.jpg",
    bio: "Former Executive Board Member at ISTE TIET.",
  },
  {
    id: "6",
    name: "Sakshat Jain",
    batch: "2023-26",
    image: "/Alumni/SakshatJain.jpg",
    bio: "Former Executive Board Member at ISTE TIET.",
  },
  {
    id: "7",
    name: "Ishaan",
    batch: "2023-2026",
    image: "/Alumni/IshaanSharma.jpg",
    bio: "Former Executive Board Member at ISTE TIET.",
  },
    
  {
    id: "8",
    name: "Ishan Pathak",
    batch: "2023-26",
    image: "/Alumni/ishaanP.jpg", 
    bio: "Former Executive Board Member at ISTE TIET.",
  },
  {
    id: "9",
    name: "Haryiank Kumra",
    batch: "2023-26",
    image: "/Alumni/HARYIANKKUMRA.jpg",
    bio: "Former Executive Board Member at ISTE TIET.",
    
  },
  {
    id: "10",
    name: "Saarthi Arora",
    batch: "2023-2026",
    image: "/Alumni/Saarthi.jpeg",
    bio: "Former Executive Committee Member at ISTE TIET.",
  },
  {
    id: "11",
    name: "Garv Chopra",
    batch: "2023-2026",
    image: "/Alumni/Garvchopra.jpg",
    bio: "Former Executive Committee Member at ISTE TIET.",
  },
  {
    id: "12",
    name: "Ayush Garg",
    batch: "2023-2026",
    image: "/Alumni/AYUSHGARG.jpg",
    bio: "Former Executive Committee Member at ISTE TIET.",
  },
  {
    id: "13",
    name: "Rishabh Garg",
    batch: "2023-2026",
    image: "/Alumni/rishabh.jpg",
    bio: "Former Executive Committee Member at ISTE TIET.",
  },
  {
    id: "14",
    name: "Dixant Sharma",
    batch: "2023-2026",
    bio: "Former Executive Committee Member at ISTE TIET.",
    image: "/Alumni/dixant.jpg",
  },
  {
    id: "15",
    name: "Tanishq Soni",
    batch: "2023-2026",
    image: "/Alumni/TanishqSoni.jpg",
    bio: "Former Executive Committee Member at ISTE TIET.",
  }
];
